---
title: "rawtoClust"
author: "Jo Hardin"
date: "6/12/2018"
output:
  pdf_document: default
  html_document: default
---


```{r, warning=FALSE, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 7, fig.height = 3, fig.align = 'center',
                      #fig.width = 30, fig.height = 10, dev = "jpeg", 
                      #fig.align = 'center', fig.keep="all", fig.path = "posterpics/", 
                      #dpi = 500, 
                      cache = TRUE, message = FALSE, warning = FALSE) 
library(tidyverse)
library(stringr)
library(cluster)
library("DESeq2")
library(amap)
library(mclust)

source("rpoSnorm.R")
source("rpoScount.R")
source("rpoSDE.R")
source("rpoSclust.R")

sessionInfo()
```


Step 1.  Decide which samples to use.  (The countfunc does pull in the 100% genes, but we don't use them here.)

```{r}
norm.samps <- c("0.00_A",  "0.00_C", "0.35_A", "0.35_C", 
                "11.59_A", "11.59_B", "11.59_C", "20.40_A", "20.40_B",  
                "48.37_A", "48.37_B", "48.37_C", "129.96_A", "129.96_B", "129.96_C", 
                "190.38_A", "190.38_B", "190.38_C")

norm.cond <- as.factor(c("0.00", "0.00", "0.35", "0.35", "11.59", "11.59", "11.59", 
                          "20.40",  "20.40", "48.37", "48.37", "48.37", "129.96", "129.96", 
                          "129.96", "190.38", "190.38", "190.38"))
```


Step 2.  Use those samples to input the dataset and create count data and tidy count data

```{r}
dp.name <- c("DMS2670_LB_NC_000913_deeper.tsv")
dp.parse <- countfunc(dp.name)
dp.count <- dp.parse$counts %>%
  dplyr::select(Geneid, feature, one_of(norm.samps), Geneid1, Geneid2, feature1, feature2,
         start.gene, end.gene, start.bnum, end.bnum, genename, bnum)

dp.countT <- dp.parse$countsT %>%
  filter(cond.samps %in% norm.samps)

# Keep only genes that have at least one sample with 5 counts
dp.gene5 <- dp.countT %>% group_by(Geneid) %>% filter(max(rawCount) >= 5) %>% 
  dplyr::select(Geneid) %>% unique()

dp.count <- dp.count %>% filter(Geneid %in% dp.gene5$Geneid)
dp.countT <- dp.countT %>% filter(Geneid %in% dp.gene5$Geneid)
```


Step 3. Normalize the full dataset

```{r}
dp.norm <- normfunc(dp.count, norm.samps, norm.cond)
```

Step 4.  Find the DE genes

```{r}
DE.samps <- c("0.00_A",   "0.00_C", "0.35_A",  "0.35_C", 
              "190.38_A", "190.38_B", "190.38_C")
DE.cond <- as.factor(c("0.00", "0.00", "0.00", "0.00", 
                       "190.38", "190.38", "190.38"))

DE.genes <- DEfunc(dp.count, DE.samps, DE.cond, DE.ref = "0.00")
```


Step 5. Cluster the normalized counts that are significant for DE

```{r}

# join normalized counts with significant DE
dp.normcount <- dp.norm$normalized %>% 
  full_join(DE.genes, by = "Geneid") %>%
  filter(padj < 0.001) %>%
  dplyr::select(-feature, -genename, -baseMean, -log2FoldChange, -lfcSE, -stat,
                -pvalue, -padj)
rownames(dp.normcount) <- dp.normcount[,"Geneid"]


dp.clustout <- clustfunc(dp.normcount, nclust = 6)

dp.countclust <- dp.clustout$countclust
dp.medoids.k6 <- dp.clustout$medoids.k

#dp.countclust.full <- dp.countclust
#dp.medoids.k6.full <- dp.medoids.k6
```



Step 6.  Plot the clusters

```{r}
#k = 6
#show medoids alone
ggplot(data = dp.medoids.k6, aes(x = `RpoS%`, y = normCountScaled)) + 
  geom_point() + geom_line(aes(y = meanScaled), size = 2) + 
  coord_cartesian(ylim = c(0,2.3)) + facet_grid(. ~ cluster) + 
  ggtitle("PAM medoids, k=6")+ ylab("Gene Expression")
```

```{r}
# k = 6, show genes with medoids
ggplot(data = dp.countclust, aes(x = `RpoS%`, y = normCountScaled, group = Geneid)) + 
  geom_point(color="blue", alpha = 0.05) + coord_cartesian(ylim = c(0,2.3)) + 
  facet_grid(. ~ cluster) +
  geom_line(aes(y = meanScaled), linetype = "dashed", color="blue", size=.1) + 
  ggtitle("Gene Expression Clustering, PAM k=6; Medoids Overlaid in black") + 
  ylab("Gene Expression") + 
  geom_line(data = dp.medoids.k6, aes(y = meanScaled), col = "black", size = 1.5) + 
  geom_point(data = dp.medoids.k6, col = "black") +
  theme(plot.title = element_text(face = "bold"))
```


Step 7.  Compare different clusterings

```{r}
adjustedRandIndex(medoids.compare$`pam$clustering.x`, medoids.compare$`pam$clustering.y`)
```
